- hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: install gpg key
      apt_key:
        id: ACCC4CF8
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
        state: present

    - apt:
        name: postgresql-9.6
        update_cache: yes
        install_recommends: yes
